version: '3.8'

services:
  anvil:
    build:
      context: .
      dockerfile: Dockerfile.anvil
    container_name: anvil
    environment:
      ANVIL_IP_ADDR: "0.0.0.0"
      FOUNDRY_DISABLE_NIGHTLY_WARNING: "true"
    working_dir: /anvil
    ports:
      - "8545:8545"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545", "-X", "POST", "-H", "Content-Type: application/json", "-d", "{\"jsonrpc\":\"2.0\",\"method\":\"eth_chainId\",\"params\":[],\"id\":1}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 