services:
  - type: web
    name: python-trading-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend/Python && gunicorn --bind 0.0.0.0:$PORT --workers 4 main:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 5049 